// <auto-generated />
using System;
using DepotService.Infraestructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DepotService.API.Migrations
{
    [DbContext(typeof(DepotDbContext))]
    [Migration("20250530114217_AddCRUDTeamsDepott")]
    partial class AddCRUDTeamsDepott
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DepotService.Domain.Entities.DepotOrderEntity", b =>
                {
                    b.Property<int>("DepotOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AssignedDepotTeamId")
                        .HasColumnType("int");

                    b.Property<Guid?>("AssignedOperatorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DeliveryDetail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SalesOrderId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("DepotOrderId");

                    b.ToTable("DepotOrders");
                });

            modelBuilder.Entity("DepotService.Domain.Entities.DepotOrderItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("DepotOrderEntityDepotOrderId")
                        .HasColumnType("int");

                    b.Property<int>("DepotOrderId")
                        .HasColumnType("int");

                    b.Property<string>("ProductBrand")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepotOrderEntityDepotOrderId");

                    b.ToTable("DepotOrderItemEntity");
                });

            modelBuilder.Entity("DepotService.Domain.Entities.DepotTeamAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DepotTeamId")
                        .HasColumnType("int");

                    b.Property<Guid>("OperatorUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("RoleInTeam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DepotTeamId");

                    b.ToTable("TeamAssignments");
                });

            modelBuilder.Entity("DepotService.Domain.Entities.DepotTeamEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TeamDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("DepotTeams");
                });

            modelBuilder.Entity("DepotService.Domain.Entities.DepotOrderItemEntity", b =>
                {
                    b.HasOne("DepotService.Domain.Entities.DepotOrderEntity", null)
                        .WithMany("Items")
                        .HasForeignKey("DepotOrderEntityDepotOrderId");
                });

            modelBuilder.Entity("DepotService.Domain.Entities.DepotTeamAssignment", b =>
                {
                    b.HasOne("DepotService.Domain.Entities.DepotTeamEntity", "depotTeamEntity")
                        .WithMany("Assignments")
                        .HasForeignKey("DepotTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("depotTeamEntity");
                });

            modelBuilder.Entity("DepotService.Domain.Entities.DepotOrderEntity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("DepotService.Domain.Entities.DepotTeamEntity", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
