/*import { LogisticOrder } from "../types/DeliveryOrderTypeDto";
import { LogisticOrder } from "../types/DeliveryOrderTypeDto";
import { PaymentType, OrderStatus } from "../types/DeliveryOrderTypeDto";
import { PriorityType } from "../types/DeliveryOrderTypeDto";

export const mockOrders: LogisticOrder[] = [
  {
    id: 1,
    status: OrderStatus.Issued,
    orderDate: "2025-10-01T10:00:00Z",
    deliveryDate: null,
    modifiedStatusDate: null,
    totalAmount: 25000,
    paymentReceipt: null,
    deliveryDetail: "Entrega en horario laboral",
    paymentType: PaymentType.Cash,
    customerId: "c1111111-aaaa-bbbb-cccc-111111111111",
    customer: {
      id: "c1111111-aaaa-bbbb-cccc-111111111111",
      firstName: "Juan",
      lastName: "Pérez",
      email: "juan.perez@example.com",
      phoneNumber: "+54 351 555 1111",
      address: "Av. Colón 1000, Córdoba",
      registrationDate: "2024-01-05T09:00:00Z",
      satisfactionDescription: null,
      satisfactionScore: 5,
      addresses: [
        {
          id: 1,
          street: "Av. Colón",
          number: "1000",
          apartment: null,
          city: "Córdoba",
          province: "Córdoba",
          country: "Argentina",
          postalCode: "5000",
          latitude: -31.4065,
          longitude: -64.191,
          formattedAddress: "Av. Colón 1000, Córdoba, Argentina",
          createdAt: "2024-01-05T09:00:00Z",
        },
      ],
    },
    items: [
      {
        id: 1,
        orderId: 1,
        productName: "Botella de Agua 2L",
        productBrand: "EcoPure",
        quantity: 10,
        packagingType: "Caja",
        unitPrice: 2500,
        total: 25000,
        salesOrderItemId: 10,
        depotOrderItemId: 20,
      },
    ],
    assignedOperatorId: null,
    assignedDeliveryTeam: null,
    assignedDeliveryTeamId: null,
    assignedDeliveryZoneId: null,
    assignedDeliveryZone: null,
    deliveryAddressId: 1,
    deliveryAddress: {
      id: 1,
      street: "Av. Colón",
      number: "1000",
      apartment: null,
      city: "Córdoba",
      province: "Córdoba",
      country: "Argentina",
      postalCode: "5000",
      latitude: -31.4065,
      longitude: -64.191,
      formattedAddress: "Av. Colón 1000, Córdoba, Argentina",
      createdAt: "2024-01-05T09:00:00Z",
    },
    depotOrderId: 100,
    salesOrderId: 200,
    priority:  PriorityType.LOW
  },
  {
    id: 2,
    status: OrderStatus.Issued,
    orderDate: "2025-09-28T09:30:00Z",
    deliveryDate: "2025-09-29T15:00:00Z",
    modifiedStatusDate: "2025-09-29T15:00:00Z",
    totalAmount: 18000,
    paymentReceipt: "REC-20250929-02",
    deliveryDetail: "Entregado sin observaciones",
    paymentType: PaymentType.Transfer,
    customerId: "c2222222-aaaa-bbbb-cccc-222222222222",
    customer: {
      id: "c2222222-aaaa-bbbb-cccc-222222222222",
      firstName: "María",
      lastName: "López",
      email: "maria.lopez@example.com",
      phoneNumber: "+54 351 555 2222",
      address: "Bv. San Juan 500, Córdoba",
      registrationDate: "2024-03-12T11:00:00Z",
      satisfactionDescription: "Excelente atención",
      satisfactionScore: 9,
      addresses: [
        {
          id: 2,
          street: "Bv. San Juan",
          number: "500",
          apartment: null,
          city: "Córdoba",
          province: "Córdoba",
          country: "Argentina",
          postalCode: "5000",
          latitude: -31.4225,
          longitude: -64.188,
          formattedAddress: "Bv. San Juan 500, Córdoba, Argentina",
          createdAt: "2024-03-12T11:00:00Z",
        },
      ],
    },
    items: [
      {
        id: 2,
        orderId: 2,
        productName: "Paquete de Harina 1kg",
        productBrand: "Molinos",
        quantity: 6,
        packagingType: "Bolsa",
        unitPrice: 3000,
        total: 18000,
        salesOrderItemId: 11,
        depotOrderItemId: 21,
      },
    ],
    assignedOperatorId: null,
    assignedDeliveryTeam: null,
    assignedDeliveryTeamId: null,
    assignedDeliveryZoneId: null,
    assignedDeliveryZone: null,
    deliveryAddressId: 2,
    deliveryAddress: {
      id: 2,
      street: "Bv. San Juan",
      number: "500",
      apartment: null,
      city: "Córdoba",
      province: "Córdoba",
      country: "Argentina",
      postalCode: "5000",
      latitude: -31.4225,
      longitude: -64.188,
      formattedAddress: "Bv. San Juan 500, Córdoba, Argentina",
      createdAt: "2024-03-12T11:00:00Z",
    },
    depotOrderId: 101,
    salesOrderId: 201,
    priority: PriorityType.HIGH
  },
    {
    id: 3,
    status: OrderStatus.Delivered,
    orderDate: "2025-09-30T14:20:00Z",
    deliveryDate: null,
    modifiedStatusDate: null,
    totalAmount: 32000,
    paymentReceipt: null,
    deliveryDetail: "Verificación pendiente por Tesorería",
    paymentType: PaymentType.Transfer,
    customerId: "c3333333-aaaa-bbbb-cccc-333333333333",
    customer: {
      id: "c3333333-aaaa-bbbb-cccc-333333333333",
      firstName: "Carlos",
      lastName: "Gómez",
      email: "carlos.gomez@example.com",
      phoneNumber: "+54 351 555 3333",
      address: "Av. Fuerza Aérea 800, Córdoba",
      registrationDate: "2024-02-15T10:00:00Z",
      satisfactionDescription: null,
      satisfactionScore: 8,
      addresses: [
        {
          id: 3,
          street: "Av. Fuerza Aérea",
          number: "800",
          apartment: null,
          city: "Córdoba",
          province: "Córdoba",
          country: "Argentina",
          postalCode: "5000",
          latitude: -31.439,
          longitude: -64.222,
          formattedAddress: "Av. Fuerza Aérea 800, Córdoba, Argentina",
          createdAt: "2024-02-15T10:00:00Z",
        },
      ],
    },
    items: [
      {
        id: 3,
        orderId: 3,
        productName: "Aceite de Girasol 1L",
        productBrand: "Natura",
        quantity: 8,
        packagingType: "Caja",
        unitPrice: 4000,
        total: 32000,
        salesOrderItemId: 12,
        depotOrderItemId: 22,
      },
    ],
    assignedOperatorId: null,
    deliveryAddressId: 3,
    deliveryAddress: {
      id: 3,
      street: "Av. Fuerza Aérea",
      number: "800",
      apartment: null,
      city: "Córdoba",
      province: "Córdoba",
      country: "Argentina",
      postalCode: "5000",
      latitude: -31.439,
      longitude: -64.222,
      formattedAddress: "Av. Fuerza Aérea 800, Córdoba, Argentina",
      createdAt: "2024-02-15T10:00:00Z",
    },
    depotOrderId: 102,
    salesOrderId: 202,
    priority: PriorityType.NORMAL,
  },
  {
    id: 4,
    status: OrderStatus.Delivered,
    orderDate: "2025-09-25T08:00:00Z",
    deliveryDate: "2025-09-26T12:00:00Z",
    modifiedStatusDate: "2025-09-26T12:00:00Z",
    totalAmount: 21000,
    paymentReceipt: "REC-20250926-04",
    deliveryDetail: "Entregado correctamente a cliente",
    paymentType: PaymentType.Cash,
    customerId: "c4444444-aaaa-bbbb-cccc-444444444444",
    customer: {
      id: "c4444444-aaaa-bbbb-cccc-444444444444",
      firstName: "Lucía",
      lastName: "Martínez",
      email: "lucia.martinez@example.com",
      phoneNumber: "+54 351 555 4444",
      address: "Obispo Trejo 120, Córdoba",
      registrationDate: "2024-06-20T12:00:00Z",
      satisfactionDescription: "Muy conforme con la entrega",
      satisfactionScore: 10,
      addresses: [
        {
          id: 4,
          street: "Obispo Trejo",
          number: "120",
          apartment: "3B",
          city: "Córdoba",
          province: "Córdoba",
          country: "Argentina",
          postalCode: "5000",
          latitude: -31.417,
          longitude: -64.187,
          formattedAddress: "Obispo Trejo 120, Córdoba, Argentina",
          createdAt: "2024-06-20T12:00:00Z",
        },
      ],
    },
    items: [
      {
        id: 4,
        orderId: 4,
        productName: "Caja de Té x100",
        productBrand: "La Virginia",
        quantity: 5,
        packagingType: "Caja",
        unitPrice: 4200,
        total: 21000,
        salesOrderItemId: 13,
        depotOrderItemId: 23,
      },
    ],
    assignedOperatorId: null,
    deliveryAddressId: 4,
    deliveryAddress: {
      id: 4,
      street: "Obispo Trejo",
      number: "120",
      apartment: "3B",
      city: "Córdoba",
      province: "Córdoba",
      country: "Argentina",
      postalCode: "5000",
      latitude: -31.417,
      longitude: -64.187,
      formattedAddress: "Obispo Trejo 120, Córdoba, Argentina",
      createdAt: "2024-06-20T12:00:00Z",
    },
    depotOrderId: 103,
    salesOrderId: 203,
    priority: PriorityType.LOW,
  },
  {
    id: 5,
    status: OrderStatus.WithIncidents,
    orderDate: "2025-09-27T13:45:00Z",
    deliveryDate: null,
    modifiedStatusDate: "2025-09-28T10:00:00Z",
    totalAmount: 15000,
    paymentReceipt: null,
    deliveryDetail: "Cancelado por el cliente antes del envío",
    paymentType: PaymentType.Transfer,
    customerId: "c5555555-aaaa-bbbb-cccc-555555555555",
    customer: {
      id: "c5555555-aaaa-bbbb-cccc-555555555555",
      firstName: "Roberto",
      lastName: "Suárez",
      email: "roberto.suarez@example.com",
      phoneNumber: "+54 351 555 5555",
      address: "Av. Patria 250, Córdoba",
      registrationDate: "2024-08-10T10:30:00Z",
      satisfactionDescription: "Cancelado antes del despacho",
      satisfactionScore: 0,
      addresses: [
        {
          id: 5,
          street: "Av. Patria",
          number: "250",
          apartment: null,
          city: "Córdoba",
          province: "Córdoba",
          country: "Argentina",
          postalCode: "5000",
          latitude: -31.420,
          longitude: -64.188,
          formattedAddress: "Av. Patria 250, Córdoba, Argentina",
          createdAt: "2024-08-10T10:30:00Z",
        },
      ],
    },
    items: [
      {
        id: 5,
        orderId: 5,
        productName: "Arroz 1kg",
        productBrand: "Gallo",
        quantity: 10,
        packagingType: "Bolsa",
        unitPrice: 1500,
        total: 15000,
        salesOrderItemId: 14,
        depotOrderItemId: 24,
      },
    ],
    assignedOperatorId: null,
    deliveryAddressId: 5,
    deliveryAddress: {
      id: 5,
      street: "Av. Patria",
      number: "250",
      apartment: null,
      city: "Córdoba",
      province: "Córdoba",
      country: "Argentina",
      postalCode: "5000",
      latitude: -31.420,
      longitude: -64.188,
      formattedAddress: "Av. Patria 250, Córdoba, Argentina",
      createdAt: "2024-08-10T10:30:00Z",
    },
    depotOrderId: 104,
    salesOrderId: 204,
    priority: PriorityType.LOW,
  },
  {
    id: 6,
    status: OrderStatus.PendingVerification,
    orderDate: "2025-09-29T09:15:00Z",
    deliveryDate: null,
    modifiedStatusDate: null,
    totalAmount: 40000,
    paymentReceipt: null,
    deliveryDetail: "Esperando verificación del pago",
    paymentType: PaymentType.Transfer,
    customerId: "c6666666-aaaa-bbbb-cccc-666666666666",
    customer: {
      id: "c6666666-aaaa-bbbb-cccc-666666666666",
      firstName: "Ana",
      lastName: "Ramírez",
      email: "ana.ramirez@example.com",
      phoneNumber: "+54 351 555 6666",
      address: "Rafael Núñez 1800, Córdoba",
      registrationDate: "2024-05-18T09:45:00Z",
      satisfactionDescription: null,
      satisfactionScore: 0,
      addresses: [
        {
          id: 6,
          street: "Rafael Núñez",
          number: "1800",
          apartment: null,
          city: "Córdoba",
          province: "Córdoba",
          country: "Argentina",
          postalCode: "5000",
          latitude: -31.389,
          longitude: -64.218,
          formattedAddress: "Rafael Núñez 1800, Córdoba, Argentina",
          createdAt: "2024-05-18T09:45:00Z",
        },
      ],
    },
    items: [
      {
        id: 6,
        orderId: 6,
        productName: "Detergente 1L",
        productBrand: "Ala",
        quantity: 20,
        packagingType: "Caja",
        unitPrice: 2000,
        total: 40000,
        salesOrderItemId: 15,
        depotOrderItemId: 25,
      },
    ],
    assignedOperatorId: null,
    deliveryAddressId: 6,
    deliveryAddress: {
      id: 6,
      street: "Rafael Núñez",
      number: "1800",
      apartment: null,
      city: "Córdoba",
      province: "Córdoba",
      country: "Argentina",
      postalCode: "5000",
      latitude: -31.389,
      longitude: -64.218,
      formattedAddress: "Rafael Núñez 1800, Córdoba, Argentina",
      createdAt: "2024-05-18T09:45:00Z",
    },
    depotOrderId: 105,
    salesOrderId: 205,
    priority: PriorityType.HIGH,
  }
];
<<<<<<< HEAD
<<<<<<< HEAD
*/

