export const mockOrders = [
  {
    id: 1,
    customer: "Juan Pérez",
    address: "Av. Colón 1000, Córdoba",
    location: { lat: -31.4065, lng: -64.1910 }, // Av. Colón
    status: "TO_DISTRIBUTE",
    payment: "CASH",
    priority: "HIGH",
  },
  {
    id: 2,
    customer: "María López",
    address: "Bv. San Juan 500, Córdoba",
    location: { lat: -31.4225, lng: -64.1880 }, // Bv. San Juan
    status: "TO_DISTRIBUTE",
    payment: "CARD",
    priority: "NORMAL",
  },
  {
    id: 3,
    customer: "Martin Gómez",
    address: "Av. Vélez Sarsfield 1500, Córdoba",
    location: { lat: -31.4480, lng: -64.1945 }, // Vélez Sarsfield
    status: "TO_DISTRIBUTE",
    payment: "CASH",
    priority: "CASI",
  },
    {
    id: 4,
    customer: "Lucía Fernández",
    address: "Av. Sabattini 2500, Córdoba",
    location: { lat: -31.4501, lng: -64.1632 },
    status: "DELIVERED",
    payment: "CASH",
    priority: "LOW",
  },
  {
    id: 5,
    customer: "Pedro Alvarez",
    address: "Av. Rafael Núñez 3500, Córdoba",
    location: { lat: -31.3568, lng: -64.2471 },
    status: "DELIVERED",
    payment: "CARD",
    priority: "NORMAL",
  },
  {
    id: 6,
    customer: "Sofía Castro",
    address: "Duarte Quirós 1200, Córdoba",
    location: { lat: -31.4209, lng: -64.2065 },
    status: "DELIVERED",
    payment: "CASH",
    priority: "HIGH",
  },
  {
    id:7,
    customer: "Martin El martinez",
    address:"Pasaje san agustin 342",
    location : {lat:-31.4201, lng: -64.2065},
    status: "PENDING_VERIFIED",
    payment: "CASH",
    priority: "HIGH",
  },
  {
    id: 8,
    customer: "Ana Torres",
    address: "Av. Fuerza Aérea 2000, Córdoba",
    location: { lat: -31.4312, lng: -64.2225 },
    status: "VERIFIED",
    payment: "CASH",
    priority: "NORMAL",
  },
  {
    id: 9,
    customer: "Diego Mariani",
    address: "Bv. Illia 800, Córdoba",
    location: { lat: -31.4205, lng: -64.1951 },
    status: "VERIFIED",
    payment: "CARD",
    priority: "LOW",
  },
  {
    id: 10,
    customer: "Valentina Ríos",
    address: "Av. Colón 1500, Córdoba",
    location: { lat: -31.4100, lng: -64.1900 },
    status: "INCIDENT",
    payment: "CASH",
    priority: "HIGH",
  },
  {
    id: 11,
    customer: "Lucas Herrera",
    address: "Bv. San Juan 1200, Córdoba",
    location: { lat: -31.4250, lng: -64.1850 },
    status: "INCIDENT",
    payment: "CARD",
    priority: "NORMAL",
  },
];
