server {
  listen 80;

  root /usr/share/nginx/html;
  index index.html;

  include /etc/nginx/mime.types;

  # Soporte para ES Modules de Expo Web
  types {
    application/javascript js mjs;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /_expo/ {
    try_files $uri =404;
  }
}