// <auto-generated />
using System;
using LogisticService.Infraestructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogisticService.Infraestructure.Migrations
{
    [DbContext(typeof(LogisticDbContext))]
    [Migration("20251111032813_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LogisticService.Domain.Entities.DeliveryIncident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DeliveryIncidentStatus")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IncidentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("LogisticOrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ReportedByOperatorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ResolutionNote")
                        .HasColumnType("longtext");

                    b.Property<bool>("Resolved")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("LogisticOrderId");

                    b.ToTable("DeliveryIncidents");
                });

            modelBuilder.Entity("LogisticService.Domain.Entities.DeliveryRejectionReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<Guid>("DeliveryOperatorId")
                        .HasColumnType("char(36)");

                    b.Property<int>("LogisticOrderId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("RejectedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("LogisticOrderId");

                    b.ToTable("DeliveryRejectionReasons");
                });

            modelBuilder.Entity("LogisticService.Domain.Entities.DeliveryTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TeamDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DeliveryTeams");
                });

            modelBuilder.Entity("LogisticService.Domain.Entities.DeliveryTeamAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("AssignedByUserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("DeliveryTeamId")
                        .HasColumnType("int");

                    b.Property<int?>("DeliveryZoneId")
                        .HasColumnType("int");

                    b.Property<int>("LogisticOrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryTeamId");

                    b.HasIndex("DeliveryZoneId");

                    b.HasIndex("LogisticOrderId");

                    b.ToTable("DeliveryTeamAssignments");
                });

            modelBuilder.Entity("LogisticService.Domain.Entities.DeliveryTeamMemberAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DeliveryTeamId")
                        .HasColumnType("int");

                    b.Property<Guid>("OperatorUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("RoleInTeam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryTeamId");

                    b.ToTable("DeliveryTeamMembers");
                });

            modelBuilder.Entity("LogisticService.Domain.Entities.DeliveryTeamZoneAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DeliveryTeamId")
                        .HasColumnType("int");

                    b.Property<int>("DeliveryZoneId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryTeamId");

                    b.HasIndex("DeliveryZoneId");

                    b.ToTable("DeliveryTeamZoneAssignments");
                });

            modelBuilder.Entity("LogisticService.Domain.Entities.DeliveryZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DeliveryZones");
                });

            modelBuilder.Entity("LogisticService.Domain.Entities.LogisticAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Apartment")
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FormattedAddress")
                        .HasColumnType("longtext");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double");

                    b.Property<Guid?>("LogisticCustomerId")
                        .HasColumnType("char(36)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PostalCode")
                        .HasColumnType("longtext");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("LogisticCustomerId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("LogisticService.Domain.Entities.LogisticCustomer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SatisfactionDescription")
                        .HasColumnType("longtext");

                    b.Property<int?>("SatisfactionScore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("LogisticService.Domain.Entities.LogisticOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AssignedDeliveryTeamId")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedDeliveryZoneId")
                        .HasColumnType("int");

                    b.Property<Guid?>("AssignedOperatorId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("char(36)");

                    b.Property<int>("DeliveryAddressId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeliveryDetail")
                        .HasColumnType("longtext");

                    b.Property<int?>("DeliveryPriority")
                        .HasColumnType("int");

                    b.Property<int>("DepotOrderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedStatusDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PaymentReceipt")
                        .HasColumnType("longtext");

                    b.Property<int?>("PaymentType")
                        .HasColumnType("int");

                    b.Property<int>("SalesOrderId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedDeliveryTeamId");

                    b.HasIndex("AssignedDeliveryZoneId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DeliveryAddressId");

                    b.ToTable("LogisticOrders");
                });

            modelBuilder.Entity("LogisticService.Domain.Entities.LogisticOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DepotOrderItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("PackagingType")
                        .HasColumnType("longtext");

                    b.Property<string>("ProductBrand")
                        .HasColumnType("longtext");

                    b.Property<string>("ProductName")
                        .HasColumnType("longtext");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SalesOrderItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("LogisticOrderItems");
                });

            modelBuilder.Entity("LogisticService.Domain.Entities.OrderStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("AverageDuration")
                        .HasColumnType("double");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LogisticOrderId")
                        .HasColumnType("int");

                    b.Property<int>("NewStatus")
                        .HasColumnType("int");

                    b.Property<int>("OldStatus")
                        .HasColumnType("int");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LogisticOrderId");

                    b.ToTable("OrderStatusHistories");
                });

            modelBuilder.Entity("LogisticService.Domain.Entities.DeliveryIncident", b =>
                {
                    b.HasOne("LogisticService.Domain.Entities.LogisticOrder", "LogisticOrder")
                        .WithMany("DeliveryIncidents")
                        .HasForeignKey("LogisticOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LogisticOrder");
                });

            modelBuilder.Entity("LogisticService.Domain.Entities.DeliveryRejectionReason", b =>
                {
                    b.HasOne("LogisticService.Domain.Entities.LogisticOrder", "LogisticOrder")
                        .WithMany("RejectionReasons")
                        .HasForeignKey("LogisticOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LogisticOrder");
                });

            modelBuilder.Entity("LogisticService.Domain.Entities.DeliveryTeamAssignment", b =>
                {
                    b.HasOne("LogisticService.Domain.Entities.DeliveryTeam", "DeliveryTeam")
                        .WithMany()
                        .HasForeignKey("DeliveryTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogisticService.Domain.Entities.DeliveryZone", "DeliveryZone")
                        .WithMany()
                        .HasForeignKey("DeliveryZoneId");

                    b.HasOne("LogisticService.Domain.Entities.LogisticOrder", "Order")
                        .WithMany()
                        .HasForeignKey("LogisticOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliveryTeam");

                    b.Navigation("DeliveryZone");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("LogisticService.Domain.Entities.DeliveryTeamMemberAssignment", b =>
                {
                    b.HasOne("LogisticService.Domain.Entities.DeliveryTeam", "DeliveryTeam")
                        .WithMany("DeliveryOperators")
                        .HasForeignKey("DeliveryTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliveryTeam");
                });

            modelBuilder.Entity("LogisticService.Domain.Entities.DeliveryTeamZoneAssignment", b =>
                {
                    b.HasOne("LogisticService.Domain.Entities.DeliveryTeam", "DeliveryTeam")
                        .WithMany("ZoneAssignments")
                        .HasForeignKey("DeliveryTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogisticService.Domain.Entities.DeliveryZone", "DeliveryZone")
                        .WithMany("ZoneAssignments")
                        .HasForeignKey("DeliveryZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliveryTeam");

                    b.Navigation("DeliveryZone");
                });

            modelBuilder.Entity("LogisticService.Domain.Entities.LogisticAddress", b =>
                {
                    b.HasOne("LogisticService.Domain.Entities.LogisticCustomer", null)
                        .WithMany("Addresses")
                        .HasForeignKey("LogisticCustomerId");
                });

            modelBuilder.Entity("LogisticService.Domain.Entities.LogisticOrder", b =>
                {
                    b.HasOne("LogisticService.Domain.Entities.DeliveryTeam", "AssignedDeliveryTeam")
                        .WithMany()
                        .HasForeignKey("AssignedDeliveryTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LogisticService.Domain.Entities.DeliveryZone", "AssignedDeliveryZone")
                        .WithMany()
                        .HasForeignKey("AssignedDeliveryZoneId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LogisticService.Domain.Entities.LogisticCustomer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogisticService.Domain.Entities.LogisticAddress", "DeliveryAddress")
                        .WithMany()
                        .HasForeignKey("DeliveryAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedDeliveryTeam");

                    b.Navigation("AssignedDeliveryZone");

                    b.Navigation("Customer");

                    b.Navigation("DeliveryAddress");
                });

            modelBuilder.Entity("LogisticService.Domain.Entities.LogisticOrderItem", b =>
                {
                    b.HasOne("LogisticService.Domain.Entities.LogisticOrder", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("LogisticService.Domain.Entities.OrderStatusHistory", b =>
                {
                    b.HasOne("LogisticService.Domain.Entities.LogisticOrder", "LogisticOrder")
                        .WithMany("StatusHistory")
                        .HasForeignKey("LogisticOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LogisticOrder");
                });

            modelBuilder.Entity("LogisticService.Domain.Entities.DeliveryTeam", b =>
                {
                    b.Navigation("DeliveryOperators");

                    b.Navigation("ZoneAssignments");
                });

            modelBuilder.Entity("LogisticService.Domain.Entities.DeliveryZone", b =>
                {
                    b.Navigation("ZoneAssignments");
                });

            modelBuilder.Entity("LogisticService.Domain.Entities.LogisticCustomer", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("LogisticService.Domain.Entities.LogisticOrder", b =>
                {
                    b.Navigation("DeliveryIncidents");

                    b.Navigation("Items");

                    b.Navigation("RejectionReasons");

                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
