// <auto-generated />
using System;
using DepotService.Infraestructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DepotService.Infraestructure.Migrations
{
    [DbContext(typeof(DepotDbContext))]
    [Migration("20251006003300_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DepotService.Domain.Entities.DepotOrderEntity", b =>
                {
                    b.Property<int>("DepotOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AssignedDepotTeamId")
                        .HasColumnType("int");

                    b.Property<Guid?>("AssignedOperatorId")
                        .HasColumnType("char(36)")
                        .HasColumnName("AssignedOperatorId");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DeliveryAddressId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeliveryDetail")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("longtext");

                    b.Property<int>("SalesOrderId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("DepotOrderId");

                    b.HasIndex("AssignedDepotTeamId");

                    b.HasIndex("DeliveryAddressId")
                        .IsUnique();

                    b.ToTable("DepotOrders");
                });

            modelBuilder.Entity("DepotService.Domain.Entities.DepotOrderItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DepotOrderEntityId")
                        .HasColumnType("int");

                    b.Property<bool>("IsReady")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PackagingType")
                        .HasColumnType("longtext");

                    b.Property<string>("ProductBrand")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SalesOrderItemId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("DepotOrderEntityId");

                    b.ToTable("DepotOrderItems");
                });

            modelBuilder.Entity("DepotService.Domain.Entities.DepotOrderMissing", b =>
                {
                    b.Property<int>("MissingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DepotOrderId")
                        .HasColumnType("int");

                    b.Property<string>("DescriptionResolution")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("MissingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MissingDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("MissingReason")
                        .HasColumnType("longtext");

                    b.Property<int>("SalesOrderId")
                        .HasColumnType("int");

                    b.HasKey("MissingId");

                    b.HasIndex("DepotOrderId");

                    b.ToTable("DepotOrderMissings");
                });

            modelBuilder.Entity("DepotService.Domain.Entities.DepotOrderMissingItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DepotOrderItemId")
                        .HasColumnType("int");

                    b.Property<int>("MissingQuantity")
                        .HasColumnType("int");

                    b.Property<int>("OrderMissingId")
                        .HasColumnType("int");

                    b.Property<string>("Packaging")
                        .HasColumnType("longtext");

                    b.Property<string>("ProductBrand")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SalesOrderItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepotOrderItemId")
                        .IsUnique();

                    b.HasIndex("OrderMissingId");

                    b.ToTable("DepotOrderMissingItem");
                });

            modelBuilder.Entity("DepotService.Domain.Entities.DepotTeamAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DepotTeamId")
                        .HasColumnType("int");

                    b.Property<Guid>("OperatorUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("RoleInTeam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DepotTeamId");

                    b.ToTable("TeamAssignments");
                });

            modelBuilder.Entity("DepotService.Domain.Entities.DepotTeamEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TeamDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("DepotTeams");
                });

            modelBuilder.Entity("DepotService.Domain.Entities.OrderAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Apartment")
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FormattedAddress")
                        .HasColumnType("longtext");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PostalCode")
                        .HasColumnType("longtext");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("OrderAddresses");
                });

            modelBuilder.Entity("DepotService.Domain.Entities.OrderStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("AverageDuration")
                        .HasColumnType("double");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NewStatus")
                        .HasColumnType("int");

                    b.Property<int>("OldStatus")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderStatusHistories");
                });

            modelBuilder.Entity("DepotService.Domain.Entities.DepotOrderEntity", b =>
                {
                    b.HasOne("DepotService.Domain.Entities.DepotTeamEntity", "AssignedDepotTeam")
                        .WithMany()
                        .HasForeignKey("AssignedDepotTeamId");

                    b.HasOne("DepotService.Domain.Entities.OrderAddress", "DeliveryAddress")
                        .WithOne("DepotOrder")
                        .HasForeignKey("DepotService.Domain.Entities.DepotOrderEntity", "DeliveryAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedDepotTeam");

                    b.Navigation("DeliveryAddress");
                });

            modelBuilder.Entity("DepotService.Domain.Entities.DepotOrderItemEntity", b =>
                {
                    b.HasOne("DepotService.Domain.Entities.DepotOrderEntity", "DepotOrderEntity")
                        .WithMany("Items")
                        .HasForeignKey("DepotOrderEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DepotOrderEntity");
                });

            modelBuilder.Entity("DepotService.Domain.Entities.DepotOrderMissing", b =>
                {
                    b.HasOne("DepotService.Domain.Entities.DepotOrderEntity", "DepotOrder")
                        .WithMany("Missings")
                        .HasForeignKey("DepotOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DepotOrder");
                });

            modelBuilder.Entity("DepotService.Domain.Entities.DepotOrderMissingItem", b =>
                {
                    b.HasOne("DepotService.Domain.Entities.DepotOrderItemEntity", "DepotOrderItem")
                        .WithOne("DepotOrderMissingItem")
                        .HasForeignKey("DepotService.Domain.Entities.DepotOrderMissingItem", "DepotOrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DepotService.Domain.Entities.DepotOrderMissing", "DepotOrderMissing")
                        .WithMany("MissingItems")
                        .HasForeignKey("OrderMissingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DepotOrderItem");

                    b.Navigation("DepotOrderMissing");
                });

            modelBuilder.Entity("DepotService.Domain.Entities.DepotTeamAssignment", b =>
                {
                    b.HasOne("DepotService.Domain.Entities.DepotTeamEntity", "depotTeamEntity")
                        .WithMany("Assignments")
                        .HasForeignKey("DepotTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("depotTeamEntity");
                });

            modelBuilder.Entity("DepotService.Domain.Entities.OrderStatusHistory", b =>
                {
                    b.HasOne("DepotService.Domain.Entities.DepotOrderEntity", "DepotOrderEntity")
                        .WithMany("StatusHistory")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DepotOrderEntity");
                });

            modelBuilder.Entity("DepotService.Domain.Entities.DepotOrderEntity", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Missings");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("DepotService.Domain.Entities.DepotOrderItemEntity", b =>
                {
                    b.Navigation("DepotOrderMissingItem");
                });

            modelBuilder.Entity("DepotService.Domain.Entities.DepotOrderMissing", b =>
                {
                    b.Navigation("MissingItems");
                });

            modelBuilder.Entity("DepotService.Domain.Entities.DepotTeamEntity", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("DepotService.Domain.Entities.OrderAddress", b =>
                {
                    b.Navigation("DepotOrder")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
